### PR TITLE
updated examples to contain timings

### PR DESCRIPTION
**Pull request by muchip**
added timings to the examples that actually perform computations in order to compare them to future implementations.

### CODE REVIEW

**Review by jdoelz — CHANGES_REQUESTED** [review]
I agree with most changes. However, in example_BlockClusterTree.out the memory requirements exceed 16GB. Could you please double check whether this is the intended behaviour? Thank you.

**Comment by muchip** [comment]
should be fixed now

**Comment by muchip** [comment]
should be fixed now

**Review by jdoelz — DISMISSED** [review]

**Review by jdoelz — APPROVED** [review]
Ok.

**Pull request merged**
